bbpress/content-single-forum.php, bbpress/loop-forums.php, bbpress/loop-topics.php, css/bbpress.min.css, front-page.php
* Småfixar för startsidan
* Uppdateringar för bättre visning av underforum
=> Multi - 2015-01-17

bbpress-functions.php, bbpress/content-archive-forum.php, bbpress/content-single-forum.php, bbpress/loop-single-forum.php, bbpress/loop-single-topic.php, bbpress/loop-topics.php, css/bbpress.min.css
Åtgärdar wpsvse/wpsv.se#32 wpsvse/wpsv.se#33 wpsvse/wpsv.se#34
=> Åtgärder för forumdelar

bbpress/content-single-forum.php, bbpress/content-single-topic.php, css/bbpress.min.css, download-monitor/content-download-box.php, download-monitor/content-download-button.php, download-monitor/content-download-filename.php, download-monitor/content-download-title.php, download-monitor/content-download-version-list.php, download-monitor/content-download.php, download-monitor/pagination.php
Uppdatering formulärknappar i forum
Standardmallar för Download Monitor
=> Multi - 2015-01-21

bbpress/content-archive-forum.php, bbpress/content-single-forum.php, bbpress/content-single-reply.php, bbpress/content-single-topic.php, bbpress/content-single-view.php, bbpress/content-topic-tag-edit.php, bbpress/form-forum.php, bbpress/form-reply.php, bbpress/form-topic-merge.php, bbpress/form-topic-split.php, bbpress/form-topic.php, bbpress/loop-replies.php, bbpress/loop-single-topic.php, css/bbpress.min.css, forum.php
Åtgärdar bland annat wpsvse/wpsv.se#40 , wpsvse/wpsv.se#41 , wpsvse/wpsv.se#42
=> Diverse åtgärder för forumvyer

bbpress/content-single-forum.php, bbpress/content-single-topic.php, bbpress/form-anonymous.php, bbpress/form-forum.php, bbpress/form-protected.php, bbpress/form-reply.php, bbpress/form-topic-merge.php, bbpress/form-topic-split.php, bbpress/form-topic-tag.php, bbpress/form-topic.php, bbpress/form-user-login.php, bbpress/form-user-lost-pass.php, bbpress/form-user-register.php, buddypress/activity/front.php, css/buddypress.css, footer.php, front-page.php
Uppdaterad formulärinramning för forum
Uppdateringar för BPs aktivitetsflöde
Uppdateringar för tydligare panelen för postform
Legend för forum i footer
=> Multi - 2015-01-25

bbpress/content-search.php, bbpress/content-single-topic.php, bbpress/feedback-no-search.php, bbpress/form-search.php, bbpress/loop-search-forum.php, bbpress/loop-search-reply.php, bbpress/loop-search-topic.php, bbpress/loop-search.php, css/bbpress.min.css, footer.php, forum.php, front-page.php
Åtgärdar bl.a wpsvse/wpsv.se#43
=> Diverse uppdateringar för forum

content-single.php, single.php, style.css
Mallar för nyheter
Uppdaterad stilmall
=> Multi - 2015-01-29

bbpress/loop-latest-single-topic.php, css/bbpress.min.css, functions.php
Stilmall för tack-funktion åtgärdar wpsvse/wpsv.se#10
Exist wrapper widgets
Mindre översättning
=> Multi - 2015-02-02

bbpress/content-single-forum.php, front-page.php
=> hrefs för '+ nytt ämne'

archive.php, content-single.php, content.php, single.php, style.css
Åtgärdar bl.a wpsvse/wpsv.se#56 och förbättrad arkivvisning
=> Uppdatering för bloggmallar

buddypress/activity/front.php, css/buddypress.css
=> Uppdatering för visa mer-knapp i aktivitsflöde

style.css
Grundläggande stilsättning för JPSharing för icon-only
=> Added JShare Styling Share Buttons on icon only

style.css
Ska vi se om det blir bättre nu då? Hoppas detta löste problemet....
=> Added fix for merge conflict

buddypress/groups/groups-loop.php, buddypress/members/single/groups/invites.php, functions.php
=> Uppdatera bp_group_avatar med större storlekar

buddypress-functions.php, js/buddypress.js
=> Fix for group search form

front-page.php
Länka gruppbeskrivning till gruppindex
=> Fix för wpsvse/wpsv.se#73

inc/wp_bootstrap_navwalker.php, style.css
=> Support for multilevel dropdowns

js/wpsvse.js
=> Add JS for scroll to top

functions.php
=> Widgets for posttypes

bbpress/form-reply.php, js/wpsvse.js
Fixes wpsvse/wpsv.se#62 & wpsvse/wpsv.se#52
=> Collapse toggle fixes

header.php
=> <link> for favicon

bbpress/loop-single-topic.php, css/bbpress.min.css
=> Better divider for forum categories

inc/adminbar.php
=> Fix for mobile view of adminbar

inc/adminbar.php
=> Extra fix for adminbar in wp-admin view

inc/extras.php, js/wpsvse.js
=> Extra fixes for collapse trigger

inc/extras.php
=> Set excerpt length on frontpage

css/bbpress.min.css, footer.php, front-page.php, style.css
Fixes wpsvse/wpsv.se#39
Ref: wpsvse/wpsv.se#90
=> Added styling and tapatalk notes

bbpress/content-latest-topics.php, bbpress/loop-latest-topics.php, front-page.php
=> Fix forum loop for frontpage

buddypress/members/single/notifications.php, buddypress/members/single/notifications/feedback-no-notifications.php, buddypress/members/single/notifications/notifications-loop.php, buddypress/members/single/notifications/read.php, buddypress/members/single/notifications/unread.php
=> Template files for notifications

buddypress/members/single/home.php
=> Include template part, notifications

404.php, style.css
=> Styling for 404

inc/extras.php
=> Add topics and replies to global search

inc/adminbar.php, style.css
=> Adminbar login

style.css
=> Fix for submenus on mobile

inc/adminbar.php
=> Enhancments for adminbar

inc/adminbar.php
=> Adminbar media queries for menu items

buddypress/groups/single/group-header.php
=> Missplaced end tag

buddypress/groups/single/group-header.php, style.css
=> Friendship btn styling

style.css
=> Group join btn styling

style.css
=> More group btn fixes

style.css
=> Group btn for front page

style.css
=> Extra fixes group btn front page

download-monitor/content-download-front.php, front-page.php, style.css
=> Front page download template and styling

download-monitor/content-download-box.php, download-monitor/search-downloads.php, page-filer.php, style.css
=> Download templates

style.css
=> General styling for main download page

download-monitor/content-download-pa-single.php, page-filer.php, style.css
=> More template modifcation for downloads

download-monitor/content-download-pa-single.php, style.css
=> Updates for single download templates

download-monitor/content-download-pa-single.php, download-monitor/content-download-pa.php, download-monitor/download-categories.php, style.css
=> Uppdates for download pages

download-monitor/content-download-pa-single.php, download-monitor/content-download-pa-thumbnail.php, download-monitor/content-download-pa.php, download-monitor/featured-downloads.php, style.css
=> Improvments for download pages

download-monitor/content-download-version-list.php, download-monitor/orderby.php, download-monitor/subcategories.php
=> More enhancments for download pages

download-monitor/content-download-front.php, front-page.php, style.css
=> Front page download buttons

buddypress/groups/front.php, front-page.php, inc/adminbar.php
Set groups to 6 on front page
Add relative url for file help page
Updates for adminbar logo and links
=> Multiple updates, small fixes

download-monitor/content-download-category.php, download-monitor/download-list.php, style.css
=> Download category view

download-monitor/content-download-widget.php
=> Download template for widget

download-monitor/download-tags.php, sidebar.php, style.css
=> Small fixes for download pages

download-monitor/content-download-front.php, style.css
=> Styling fixes for front page downloads

bbpress/content-archive-forum.php, bbpress/content-single-forum.php, style.css
=> Multiple small fixes

sidebar.php
=> Fix for multi widget sections

functions.php, inc/shortcodes.php, page-full.php, page.php, searchform.php, style.css
Box shortcodes - wpsvse/wpsv.se#118
Fix for content lists
Searchform fix
=> Multiple updates

css/bbpress.min.css, style.css
=> Small fix for tag display

bbpress/form-user-login.php, bbpress/form-user-lost-pass.php, css/bbpress.min.css, extras/page-user-login.php, extras/page-user-lost-pass.php, extras/page-user-register.php, forum.php
=> Templates and styling for register and login

style.css
=> Remove break-all for sidebar

buddypress/members/register.php
=> First go at registration page

buddypress/members/register.php
=> Update for registration page

css/buddypress.css
=> Last fix for reg page

buddypress/members/single/profile/edit.php, css/buddypress.css
=> Updates for profile edit page

style.css
=> Fix for items for memebers

style.css
=> Fix for group count item styling

buddypress/groups/create.php
=> Some translation

style.css
=> Code highlight styling

style.css
=> Partial fix for viewport bugs

buddypress/activity/front.php, style.css
=> Add some bootstrap markup and styling fixes for viewport bug

css/bbpress.min.css, style.css
=> Update styling for bbPress topic form

js/wpsvse.js
=> Fix Magnific Popup trigger for inserts

buddypress-functions.php, css/wpsvse_adminbar.css, functions.php, inc/branding.php, inc/extras.php
Blog posts added to activity stream wpsvse/wpsv.se#133
=> General trimming of theme function files

functions.php, inc/extras.php
wpsvse/wpsv.se#131
wpsvse/wpsv.se#98
=> Move forum editor functions to plugin

css/bbpress.min.css, style.css
=> Forum editor styling

css/buddypress.css
=> Remove a float to much

buddypress/groups/front.php, style.css
=> Fix for group stacking on front page

style.css
=> Better contrast for menu

css/buddypress.css, footer.php
=> Antispam styling and register form clean up

css/buddypress.css, style.css
Styling for reg errors …
Fix twitter widget padding …
=> Styling fixes

style.css
=> Bug fix for friendship btn

css/bbpress.css, style.css
=> Fix for list-style in forum posts

buddypress/groups/create.php, functions.php
=> Widget for group creation rules

css/bbpress.css
=> Padding for lists in forum posts

buddypress/members/register.php, css/buddypress.css, footer.php, functions.php
Fixes wpsvse/wpsv.se#156
Fixes wpsvse/wpsv.se#153
=> TOS register parts and widget fixes

css/buddypress.css
=> Fixes for TOS styling

bbpress/form-topic-split.php, css/bbpress.css, front-page.php
=> Quote padding an list-style

css/bbpress.css
=> Styling updates for GD bbPress Toolbox

inc/extras.php
=> Allow admins to use HTML in group desc.

style.css
=> Better styling for image captions

forum.php, style.css
=> Share button in forums and styling fix

download-monitor/content-download-category.php, download-monitor/content-download-front.php, download-monitor/content-download-pa-thumbnail.php, download-monitor/content-download-pa.php, download-monitor/content-download-widget.php
=> Updated templates for extra download att

download-monitor/content-download-category.php, download-monitor/content-download-front.php, download-monitor/content-download-pa-thumbnail.php, download-monitor/content-download-pa.php, download-monitor/content-download-widget.php
=> Use correct global for dlm templates

download-monitor/content-download-category.php, download-monitor/content-download-front.php, download-monitor/content-download-pa-thumbnail.php, download-monitor/content-download-pa.php, download-monitor/content-download-widget.php, inc/metaboxes.php
=> Download extra meta and template updates

js/wpsvse.js
=> Open external links in new tab/window

archive-wpsvse_projects.php, content-projects.php, content-single-project.php, single-wpsvse_projects.php, style.css
=> Translation project templates

archive-wpsvse_projects.php, content-projects.php
=> Sort order and grid fix

content-projects.php, content-single-project.php, style.css, taxonomy-wpsvse_project_type.php
=> Translation project updates

archive-wpsvse_translators.php, content-projects.php, content-single-project.php, content-single-translator.php, content-translators.php, single-wpsvse_translators.php, style.css
=> More translation project templates

search.php
=> Fix Marcus boo boo

archive-wpsvse_projects.php, archive-wpsvse_translators.php, sidebar.php, taxonomy-wpsvse_project_type.php, translator-search.php
=> Finalizing template updates for translation projects

comments.php, functions.php, inc/wpsvse_comments.php
=> Create proper comment templates

style.css
=> Comments styling

buddypress-functions.php
=> Disable profile textarea editor for BP

archive-wpsvse_projects.php, archive-wpsvse_translators.php, comments.php, inc/wpsvse_comments.php, style.css
=> Update for pingbacks in comment template

404.php, functions.php, page-slack.php
Also added a widget to start changes for the Twitter widgets, wpsvse/wpsv.se#180
=> Page template and widgets for better Slack invites

bbpress/form-reply.php, bbpress/form-topic.php, css/bbpress.css, download-monitor/content-download-box.php, download-monitor/content-download-button.php, download-monitor/content-download-category.php, download-monitor/content-download-filename.php, download-monitor/content-download-pa-single.php, download-monitor/content-download-pa-thumbnail.php, download-monitor/content-download-pa.php, download-monitor/content-download-title.php, download-monitor/content-download-version-list.php, download-monitor/content-download-widget.php, download-monitor/content-download.php, front-page.php, style.css
=> Change to bbcode toolbar for bbPress and Updated download templates

bbpress/form-bbcodes.php, bbpress/form-reply.php, bbpress/form-topic.php, style.css
=> Use bbp_get_template_part instead

style.css
=> Updated styles for docs

front-page.php, functions.php
=> Create widget areas for twitter widgets

functions.php, template-parts/gp-templates/css/theme.css, template-parts/gp-templates/header.php
=> Add menu and widget for gp

style.css, template-parts/gp-templates/css/theme.css
=> Fix for gp menu and supposition for main menu

style.css
=> Version bump 4.1

css/bbpress.css, footer.php, inc/extras.php, js/wpsvse.js, style.css
* Conditional loading of iframe JS for GP
* Style fixes
* Add po and pot to allowed file types
=> Multiple smaller fixes

css/bbpress.css, css/buddypress.css, style.css
=> CSS trim for bbPress, WP and BP

style.css
=> Remove link :focus

buddypress/members/register.php, css/wpsvse_adminbar.css, style.css
=> Social login and version bump

buddypress/members/register.php
=> Social login fix for register page
